# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 086cbff8810be74efe0de166b8f02db75092db4e64aee68c7b28a7c8774906b1a13f5b576f606e4d86722843e9a1aa0521d3bb03041a5783509af8fb52bdf5f7

test:
  secret_key_base: 0ff56b1498c1afc93126c055976526179ecff96f3c17feee2b08ab2a61e0ffccefcfd1ba1e563a70ba42ad5f5530c51e7537a3e6446500f2db8da4e5535b3d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
